---
- name: Set SELinux state to disabled
  ansible.builtin.seboolean:
    name: selinux
    state: disabled
- name: Remove old Docker versions
  ansible.builtin.dnf:
    name: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
    state: absent
- name: Install necessary packages
  ansible.builtin.dnf:
    name: dnf-plugins-core,chrony
    state: present
- name: Enable chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes
- name: Add Docker's official repository
  ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce,docker-ce-cli,containerd.io,docker-compose-plugin,docker-compose
    state: present
- name: Add rusik to docker group
  ansible.builtin.user:
    name: rusik
    groups: docker
    append: yes
- name: Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
